[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49982
Protocol = 'http'
StartupMsg = 'device mqtt started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

# Driver configs
[Driver]
IncomingSchema = 'tcp'
IncomingHost = '0.0.0.0'
IncomingPort = '1883'
IncomingUser = 'admin'
IncomingPassword = 'public'
IncomingQos = '0'
IncomingKeepAlive = '3600'
IncomingClientId = 'IncomingDataSubscriber'
IncomingTopic = 'DataTopic'
ResponseSchema = 'tcp'
ResponseHost = '0.0.0.0'
ResponsePort = '1883'
ResponseUser = 'admin'
ResponsePassword = 'public'
ResponseQos = '0'
ResponseKeepAlive = '3600'
ResponseClientId = 'CommandResponseSubscriber'
ResponseTopic = 'ResponseTopic'
DiscoverySchema = 'tcp'
DiscoveryHost = '0.0.0.0'
DiscoveryPort = '1883'
DiscoveryUser = 'admin'
DiscoveryPassword = 'public'
DiscoveryClientId = 'DiscoveryPublisher'
DiscoveryTopic = 'DiscoveryTopic'
DiscoveryResponseSchema = 'tcp'
DiscoveryResponseHost = '0.0.0.0'
DiscoveryResponsePort = '1883'
DiscoveryResponseUser = 'admin'
DiscoveryResponsePassword = 'public'
DiscoveryResponseQos = '0'
DiscoveryResponseKeepAlive = '3600'
DiscoveryResponseClientId = 'DiscoveryResponseSubscriber'
DiscoveryResponseTopic = 'DiscoveryResponseTopic'
DefaultCommandSchema = 'tcp'
DefaultCommandHost = '0.0.0.0'
DefaultCommandPort = '1883'
DefaultCommandUser = 'admin'
DefaultCommandPassword = 'public'
DefaultCommandClientId = 'CommandPublisher'
DefaultCommandTopic = 'CommandTopic'
ConnEstablishingRetry = '10'
ConnRetryWaitTime = '5'
